### ISSUE TITLE
Problem when Cloning and setting up the environment

### ISSUE THREAD

**Issue by ethancohen123** [GSK-AI/mocop#1]
Hi,
I have tried to setup the environment following your instructions but I got stuck at source .env , getting this error 

bash: cd: .env: No such file or directory

Is there something missing or am I missing something ? 

Thanks

**Comment by cuongqn** [comment]
Hi! The file was in ignored by git in the initial commit. It should be there now. Thank you for catching it!

**Comment by ethancohen123** [comment]
Thanks !
